version: '2.1'
services:
  postgres:
    image: postgres:10
    container_name: paysend-postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=b93uBESRp0zEE0TK
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - paysend-network
  app:
    container_name: paysend-app
    build:
      context: .
      dockerfile: Dockerfile
    image: paysend-app:latest
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - paysend-network
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5

networks:
  paysend-network:
    driver: bridge