spring:
  flyway:
    locations: classpath:/db/migration
  datasource:
    url: jdbc:postgresql://${spring.datasource.database.host}:${spring.datasource.database.port}/${spring.datasource.database.name}
    database:
      host: postgres
      port: 5432
      name: bank
    username: paysend
    password: paysend
